### ISSUE TITLE
Simplify logging

### ISSUE THREAD

**Issue by csherwood-usgs** [pyviz-topics/holodoodler#32]
This is mostly for @dbuscombe@usgs.gov : I noticed you output lines with the time stamp for the logger with code in `image_segmentation.py` like this:
```
logger.debug(datetime.now().strftime("%Y-%m-%d-%H-%M-%S"))
logger.debug('One-hot labels spatially filtered')
```
You don't need to do that...the time stamp comes out on each line like so:
```
05/25/2022 04:06:07 PM	DEBUG	image_segmentation:613	2022-05-25-16-06-07
05/25/2022 04:06:07 PM	DEBUG	image_segmentation:614	One-hot labels filtered
```
This behavior is controlled by a big dict that describes the default logging parameters (line 17 in `app.py`), applied in line 49.

Maybe you want to remove these lines to slim down both your code and the log file...or maybe you want to leave those in so you can still get timing with a simpler invocation of the logger. Just noticed it and thought I'd point it out.

**Comment by dbuscombe-usgs** [comment]
Agree. I'll revisit the way logging occurs when I repackage the doodler segmentation codes into a stand-alone repository that can serve as the common function set for both labeling interfaces. Thanks for all your great suggestions!

**Comment by ddbuscombe** [comment]
`doodler-engine` functions do not timestamps to logging commands, so we can safely close this. Thanks for the suggestion Chris
